# Generated by Django 4.2.7 on 2024-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Готов', 'Готов'), ('Заказ выдан', 'Заказ выдан')], default='Принят', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
