# Generated by Django 4.2.7 on 2024-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Готов', 'Готов'), ('Заказ выдан', 'Заказ выдан')], default='Принят', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
